name: C/C++ CI

on: [push]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
        # Github Actions requires a single row to be added to the build matrix.
        # See https://help.github.com/en/articles/workflow-syntax-for-github-actions.
        # see https://github.com/DaanDeMeyer/reproc/blob/master/.github/workflows/main.yml.
        # see https://github.community/t5/GitHub-Actions/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558.
        # see https://github.com/svenstaro/proxyboi/blob/master/.github/workflows/publish.yml.
      matrix:
        name: [
          ubuntu-18-all,
          ubuntu-18-everything,
          ubuntu-16-all,
          ubuntu-16-everything,
        ]
        
        include:
          - name: ubuntu-18-all
            os: ubuntu-18.04
            DOITPROG: "all"
            version: "1"
            skiping: "0"
          
          - name: ubuntu-18-everything
            os: ubuntu-18.04
            DOITPROG: "everything"
            version: "2"
            skiping: "0"

          - name: ubuntu-16-all
            os: ubuntu-16.04
            DOITPROG: "all"
            version: "3"
            skiping: "0"            
          
          - name: ubuntu-16-everything
            os: ubuntu-16.04
            DOITPROG: "everything"
            version: "4"
            skiping: "0"
      

#    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies on Linux
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt update && sudo apt install -y --no-install-recommends binutils-dev liblzma-dev syslinux genisoimage
      if: matrix.os == 'ubuntu-16.04'
      run: sudo apt update && sudo apt install -y --no-install-recommends binutils-dev liblzma-dev syslinux genisoimage
    - uses: actions/checkout@v1
   #  - name: configure
   #   run: ./configure
    - name: make -C src ${{ matrix.DOITPROG }}
      run: make -C src ${{ matrix.DOITPROG }}
    #- name: make -C src everything
    #  run: make -C src everything
    #- name: bin-x86_64-linux/tests.linux
    #  run: make -C src bin-x86_64-linux/tests.linux && ./bin-x86_64-linux/tests.linux
    #- name: bin-i386-linux/tests.linux
    #  run: make -C src bin-i386-linux/tests.linux && ./bin-i386-linux/tests.linux
   #valgrind ./bin-x86_64-linux/tests.linux
   #  valgrind ./bin-i386-linux/tests.linux
