name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Dependencies on Linux
      if: matrix.platform == 'ubuntu-18.04'
      run: sudo apt update && sudo apt install -y --no-install-recommends binutils-dev liblzma-dev syslinux genisoimage
    - uses: actions/checkout@v1
   #  - name: configure
   #   run: ./configure
    - name: make -C src all
      run: make -C src all
    - name: make -C src everything
      run: make -C src everything
    - name: bin-x86_64-linux/tests.linux
      run: make -C src bin-x86_64-linux/tests.linux && ./bin-x86_64-linux/tests.linux
    - name: bin-i386-linux/tests.linux
      run: make -C src bin-i386-linux/tests.linux && ./bin-i386-linux/tests.linux
   #valgrind ./bin-x86_64-linux/tests.linux
   #  valgrind ./bin-i386-linux/tests.linux
